#!/usr/bin/env bash

if command -v golangci-lint &> /dev/null
then
    echo "golangci-lint already installed"
    exit
fi

curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

echo "golangci-lint successfully installed"
