name: "Lint"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    timeout-minutes: 30
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.22
          cache: true

      - name: Linelint
        uses: fernandrone/linelint@0.0.6
        id: newline-lint

      - name: Prepare Environment
        run: |
          make prepare

      - name: Golang CI Lint
        id: go-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          skip-cache: true
          args: --timeout=10m

      - uses: github/super-linter/slim@v5
        id: lint
        env:
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_SQL: true
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}