name: "Test & Build"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_build:
    timeout-minutes: 30
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.22
          cache: true

      - name: Prepare Environment
        run: |
          make prepare

      - name: Run Go Test
        id: test
        run: make run-tests

      - name: Build Go App
        id: build
        run: make build